"""consultation_chat

Revision ID: 017a309711bf
Revises: 5080ce142dc2
Create Date: 2026-06-25 18:12:05.630865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017a309711bf'
down_revision: Union[str, Sequence[str], None] = '5080ce142dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sender_id', sa.UUID(), nullable=False))
    op.add_column('chat_messages', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('chat_messages', sa.Column('message_type', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'user_message')
    op.drop_column('chat_messages', 'ai_response')
    op.drop_column('chat_messages', 'tokens_used')
    op.drop_column('chat_messages', 'intent')
    op.add_column('chat_sessions', sa.Column('consultation_id', sa.UUID(), nullable=False))
    op.add_column('chat_sessions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('chat_sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chat_sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_consultation_id'), 'chat_sessions', ['consultation_id'], unique=True)
    op.drop_constraint(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_sessions_consultation_id'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_column('chat_sessions', 'ended_at')
    op.drop_column('chat_sessions', 'started_at')
    op.drop_column('chat_sessions', 'is_active')
    op.drop_column('chat_sessions', 'consultation_id')
    op.add_column('chat_messages', sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'message_type')
    op.drop_column('chat_messages', 'message')
    op.drop_column('chat_messages', 'sender_id')
    # ### end Alembic commands ###
