"""update transaction model

Revision ID: 329d341178aa
Revises: b7f953c8d2fc
Create Date: 2026-06-05 14:47:54.011674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329d341178aa'
down_revision: Union[str, Sequence[str], None] = 'b7f953c8d2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transactions', ['transaction_reference'])
    op.drop_constraint(op.f('transactions_client_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_client_id_fkey'), 'transactions', 'users', ['client_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='unique')
    # ### end Alembic commands ###
