"""update consultation flow

Revision ID: 5080ce142dc2
Revises: 934e95513db3
Create Date: 2026-06-25 17:07:18.624858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5080ce142dc2'
down_revision: Union[str, Sequence[str], None] = '934e95513db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('consultant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('consultant_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_charged', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocated_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_client_id'), 'consultations', ['client_id'], unique=False)
    op.create_index(op.f('ix_consultations_consultant_id'), 'consultations', ['consultant_id'], unique=False)
    op.create_foreign_key(None, 'consultation_status_history', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'refund_requests', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'consultations', ['consultation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'refund_requests', type_='foreignkey')
    op.drop_constraint(None, 'consultation_status_history', type_='foreignkey')
    op.drop_index(op.f('ix_consultations_consultant_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_client_id'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
