"""consultation prepaid flow

Revision ID: 934e95513db3
Revises: da9a275f520f
Create Date: 2026-06-23 17:17:31.355828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934e95513db3'
down_revision: Union[str, Sequence[str], None] = 'da9a275f520f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('consultations', sa.Column('allocated_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'allocated_minutes')
    op.drop_column('consultations', 'requested_amount')
    # ### end Alembic commands ###
